.TH SAUCE 1 "AUGUST 2014" Linux "User Manuals"
.SH NAME
.PP
sauce \- displays Standard Architecture for Universal Comment Extensions meta data
.SH SYNOPSIS
.PP
\fB\fCsauce\fR \fB\fC[-V]\fR
.PP
\fB\fCsauce\fR \fIfiles\fP ...
.SH DESCRIPTION
.PP
\fB\fCsauce\fR parses the embedded SAUCE meta data packets in files, showing
all the details for the detected data type and file type.
.SH OPTIONS
.TP
\fB\fC-V --version\fR
    Display version information
.SH BUGS
.PP
For bugs and feature requests, you can use the GitHub issue tracker at
.UR https://github.com/tehmaze/piece-c
.UE
.SH AUTHOR
.PP
Wijnand Modderman\-Lenstra 
.MT maze@pyt0n.org
.ME
.SH SEE ALSO
.PP
.BR piece (1), 
Acid.org SAUCE specification
.UR http://www.acid.org/info/sauce/sauce.html
.UE
