#!/usr/bin/env python2

import os
import sys
from PIL import Image
from StringIO import StringIO


def load_image(filename_or_str):
    if os.path.isfile(filename_or_str):
        filename_or_str = file(filename_or_str).read()

    blob = StringIO(filename_or_str.decode('base64'))
    blob.seek(0)
    image = Image.open(blob)

    if image.mode != '1':
        image = image.convert('1')

    return image


def run():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', required=True)
    parser.add_argument('filename_or_string')

    option = parser.parse_args()

    image = load_image(option.filename_or_string)
    image.save(option.output)


if __name__ == '__main__':
    sys.exit(run())
