language: c

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

before_install:
 - sudo apt-get update
 - sudo apt-get install -y python-imaging python-jinja2 libgd-dev libgd2-xpm-dev
 - wget http://gfx.bbs.ninja/pack/lurk/to/pc/2006/sense25/m0-mario.ans
 - wget http://gfx.bbs.ninja/pack/lurk/to/pc/2014/blocktronics_wtf4/2m-sweetprince.xb

script:
 - ./configure || cat wright.log
 - make piece sauce
 - ./sauce m0-mario.ans
 - ./piece -v -o m0-mario.png m0-mario.ans
 - ./piece -v -o 2m-sweetprince.png 2m-sweetprince.xb
